In [ ]:
from google.colab import files
uploaded = files.upload()

Saving sales_data.csv to sales_data.csv

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("sales_data.csv")
df.shape

(54, 6)

In [ ]:
df.head()

  Order_ID          Name        Date Region     Product    Sales
0  ORD0001  Aarav Sharma  2026-04-13   West    Keyboard  55386.0
1  ORD0002     Priya Das  2026-05-02   EAST  Headphones  44631.0
2  ORD0003     Rahul Sen  2026-04-14   west  Headphones  67721.0
3  ORD0004    Ananya Roy  2026-02-22  South     Monitor  65425.0
4  ORD0005  Vikram Singh  2026-02-07  NORTH     Monitor  54207.0

In [ ]:
df.tail()

   Order_ID          Name        Date Region     Product    Sales
49  ORD0050   Karan Patel  2026-06-25   east  Headphones  23900.0
50  ORD0015     Rohan Das  2026-06-01  NORTH      Laptop  72500.0
51  ORD0020  Sanjay Ghosh  2026-06-11  SOUTH      Laptop  68400.0
52  ORD0030   Karan Patel  2026-04-30   West     Printer  16400.0
53  ORD0042  Aarav Sharma  2026-04-20   west      Laptop  74800.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Order_ID  54 non-null     object
 1   Name      53 non-null     object
 2   Date      53 non-null     object
 3   Region    52 non-null     object
 4   Product   53 non-null     object
 5   Sales     52 non-null     float64
dtypes: float64(1), object(5)
memory usage: 2.7+ KB

In [ ]:
df.describe()

              Sales
count     52.000000
mean   38262.442308
std    21230.952351
min     3247.000000
25%    19425.000000
50%    33950.000000
75%    56125.000000
max    74800.000000

In [ ]:
df.columns

Index(['Order_ID', 'Name', 'Date', 'Region', 'Product', 'Sales'], dtype='object')

In [ ]:
df.isna().sum()

Order_ID    0
Name        1
Date        1
Region      2
Product     1
Sales       2
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(4)

In [ ]:
df[df["Name"].isnull()]

   Order_ID Name        Date Region Product    Sales
15  ORD0016  NaN  2026-03-15  South  Mobile  31500.0

In [ ]:
df["Name"] = df["Name"].fillna("Unknown")

In [ ]:
df.loc[df["Product"].isnull(), ["Product", "Sales"]]

   Product    Sales
21     NaN  38700.0

In [ ]:
filtered_products = df[(df['Sales'] > 38000) & (df['Sales'] < 40000)]
print(filtered_products)

   Order_ID          Name        Date Region  Product    Sales
21  ORD0022  Aarav Sharma  2026-02-12   west      NaN  38700.0
31  ORD0032  Sourav Dutta  2026-06-22  south  Monitor  39800.0
42  ORD0043     Priya Das  2026-05-06    NaN  Monitor  38600.0

In [ ]:
df["Product"] = df["Product"].fillna("Monitor")

In [ ]:
df.isna().sum()

Order_ID    0
Name        0
Date        1
Region      2
Product     0
Sales       2
dtype: int64

In [ ]:
df.loc[df["Region"].isnull(), ["Name", "Region", "Date"]]

          Name Region        Date
7   Riya Ghosh    NaN  2026-01-15
42   Priya Das    NaN  2026-05-06

In [ ]:
df["Region"] = df["Region"].fillna("Unknown")

In [ ]:
df.loc[df["Sales"].isnull(), ["Product", "Sales"]]

     Product  Sales
13  Keyboard    NaN
46   Printer    NaN

In [ ]:
keyboard_products = df[df['Product'] == 'Keyboard'][['Product', 'Sales']]
print(keyboard_products)

     Product     Sales
0   Keyboard  55386.00
5   Keyboard  26158.00
13  Keyboard  19777.71
20  Keyboard  12300.00
27  Keyboard   9800.00
33  Keyboard  11200.00
38  Keyboard  12700.00
44  Keyboard  10900.00

In [ ]:
average_keyboard_price = round(keyboard_products['Sales'].mean(), 2)
print(f"The average price of keyboards is: {average_keyboard_price}")

The average price of keyboards is: 19777.71

In [ ]:
df.loc[(df['Product'] == 'Keyboard') & (df['Sales'].isnull()), 'Sales'] = average_keyboard_price
print(df[df['Product'] == 'Keyboard'])

   Order_ID           Name        Date Region   Product     Sales
0   ORD0001   Aarav Sharma  2026-04-13   West  Keyboard  55386.00
5   ORD0006    Sneha Gupta  2026-02-27  south  Keyboard  26158.00
13  ORD0014     Tanya Paul  2026-05-22   West  Keyboard  19777.71
20  ORD0021    Nisha Patel  2026-01-22   East  Keyboard  12300.00
27  ORD0028    Arjun Mehta  2026-02-16  SOUTH  Keyboard   9800.00
33  ORD0034     Amit Kumar  2026-02-21   west  Keyboard  11200.00
38  ORD0039  Ishita Sharma  2026-01-18  north  Keyboard  12700.00
44  ORD0045     Ananya Roy  2026-01-27  south  Keyboard  10900.00

In [ ]:
printer_products = df[df['Product'] == 'Printer'][['Product', 'Sales']]
print(printer_products)

    Product    Sales
7   Printer  36273.0
12  Printer  18900.0
18  Printer  19600.0
23  Printer  17500.0
29  Printer  16400.0
35  Printer  15300.0
40  Printer  18100.0
46  Printer      NaN
52  Printer  16400.0

In [ ]:
average_printer_price = round(printer_products['Sales'].mean(), 2)
print(f"The average price of printer is: {average_printer_price}")

The average price of printer is: 19809.12

In [ ]:
df.loc[(df['Product'] == 'Printer') & (df['Sales'].isnull()), 'Sales'] = average_printer_price
print(df[df['Product'] == 'Printer'])

   Order_ID           Name        Date   Region  Product     Sales
7   ORD0008     Riya Ghosh  2026-01-15  Unknown  Printer  36273.00
12  ORD0013     Amit Kumar  2026-04-18     EAST  Printer  18900.00
18  ORD0019  Ishita Sharma  2026-05-14    north  Printer  19600.00
23  ORD0024      Rahul Sen  2026-04-25    south  Printer  17500.00
29  ORD0030    Karan Patel  2026-04-30     West  Printer  16400.00
35  ORD0036      Rohan Das  2026-04-14    NORTH  Printer  15300.00
40  ORD0041    Nisha Patel  2026-03-12     EAST  Printer  18100.00
46  ORD0047    Sneha Gupta  2026-03-23     West  Printer  19809.12
52  ORD0030    Karan Patel  2026-04-30     West  Printer  16400.00

In [ ]:
df.duplicated().sum()

np.int64(4)

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.isna().sum()

Order_ID    0
Name        0
Date        0
Region      0
Product     0
Sales       0
dtype: int64

In [ ]:
df["Date"] = df["Date"].fillna("0000-00-00")

/tmp/ipykernel_782/3431167177.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Date"] = df["Date"].fillna("0000-00-00")

In [ ]:
df.to_csv("cleaned_sales.xlsx", index=False)

In [ ]:
df.to_excel("cleaned_sales.xlsx", index=False)