In [ ]:
from google.colab import files
uploaded = files.upload()

Saving customers (1).csv to customers (1).csv

In [ ]:
import pandas as pd
import numpy as np

customers = pd.read_csv("customers (1).csv")
print(f"Customers shape: {customers.shape}")

orders = pd.read_csv("orders.csv")
print(f"orders shape: {orders.shape}")

Customers shape: (40, 3)
orders shape: (100, 3)

In [ ]:
customers.head()

   customer_id   region signup_date
0            1    North  2022-01-26
1            2     East  2022-09-08
2            3    South  2022-05-23
3            4    North  2023-11-24
4            5  Central  2022-03-31

In [ ]:
orders.head()

   customer_id  order_amount  order_date
0           14        340.03  2024-12-25
1            5        310.43  2024-03-28
2           35        368.63  2024-03-24
3           30        199.04  2024-11-23
4           36        121.51  2024-06-15

In [ ]:
merged_df = pd.merge(
    orders,
    customers,
    on="customer_id",
    how="inner")

In [ ]:
print("Merged DataFrame:")
print(merged_df.head())

Merged DataFrame:
   customer_id  order_amount  order_date   region signup_date
0           14        340.03  2024-12-25  Central  2022-10-12
1            5        310.43  2024-03-28  Central  2022-03-31
2           35        368.63  2024-03-24     East  2022-03-23
3           30        199.04  2024-11-23  Central  2024-06-01
4           36        121.51  2024-06-15    South  2024-06-06

In [ ]:
region_summary = (
    merged_df
    .groupby("region")["order_amount"]
    .agg(
        total_order_amount="sum",
        average_order_amount="mean"
    )
    .reset_index()
)
print(region_summary)

    region  total_order_amount  average_order_amount
0  Central             5272.45            263.622500
1     East             6479.46            249.210000
2    North             5468.09            218.723600
3    South             4665.93            202.866522
4     West             1980.93            330.155000